### ISSUE TITLE
About the Dockerfile

### ISSUE THREAD

**Issue by mpolinowski** [gofiber/boilerplate#27]
First, I want to thank you for sharing this boilerplate. I just started to get to know Fiber and this was a great help. Thank you so much!

I did find the Dockerfile you are using a bit complicated - I know it is an example from the Docker documentation and it does work. The first problem that I ran into was that the image generated in the second step - in the scope of my Docker abilities - could not be renamed. So I always ended up with a generic ID (makes it a bit more complicated to add the image into a Docker-Compose or Kubernetes workflow). And then there is the issue of keeping the container running in the background.

Is there a reason behind the setup you choose that I am not seeing? Or is this a better solution:

https://github.com/mpolinowski/boilerplate

**Comment by WLun001** [comment]
I wasn't the one who wrote the Dockerfile, but there is my thought. 
Generally we want to create smaller docker image size, we can achieve by multistage build as shown in the Dockerfile. 
Without the second stage, the image size could be few hundred MBs. With multi stage build, could down to less than 30MB or lower. Due to Go is compile to single binary and can run on linux without required VM or runtime. 

And you should give the image name on build, instead of rely on auto generated image name

for example 
```bash
 docker build -t your-image-name:1.0 .
```
Then you can refer the image as `your-image-name:1.0`

**Comment by mpolinowski** [comment]
Hi @WLun001 ,

thank you for your reply.

I understand what the two-stage Dockerfile is solving. But take a look at this comparison:

![Untitled](https://user-images.githubusercontent.com/18694428/98469785-a81f8a00-221c-11eb-9487-946c538688bb.png)

I used your command ` docker build -t your-image-name:1.0 .` to build the image from the Dockerfile in this repository. It downloaded the golang:1.15 and alpine:latest image and build the two images on top (marked in green). Only the build step is assigned the name `your-image-name`. The image that you actually want to use can only be assigned by the image ID.

My solution downloaded golang:1.15-alpine and created a single image which I called boilerplate_ingress.


So I used up 299MB + 309MB = __608MB__  __vs.__ 839 + 5.57 + 14.9 + 1010  = __1869 MB__

**Comment by WLun001** [comment]
No, the image you wanted to use is `your-image-name` The `<none` can be safely removed after build

**Comment by mpolinowski** [comment]
Ok I think I am seeing my mistake - the `your-image-name` image` is not the build image but the image that contains the ready to use binary.

I am a bit confused right now, because that is what I originally thought but I could not get it to run. I must have made a mistake there somewhere - let me check.

**Comment by mpolinowski** [comment]
Ok, I found a couple of problems why - I believe - this did not work for me in the first place:

https://github.com/gofiber/boilerplate/compare/master...mpolinowski:master

Those are the changes I had to make - 

1. Source (HTML) was copied from ./public and not ./static/public
2. Fiber was listening on port 3001 not 3000
3. And the public directory was set to ./static/public instead of ./public

**Comment by WLun001** [comment]
@mpolinowski I think should always use `./static/public` for consistency, on dockerfile and `app.go`

would accept PR for that fix, would you like to try?

**Comment by mpolinowski** [comment]
@WLun001 I made the changes and tested the container. You can check the pull request.
