### ISSUE TITLE
[ discussion about routing ]

### ISSUE THREAD

**Issue by firmanJS** [gofiber/boilerplate#37]
Hello
maybe this is just a little suggestion why the router is not separated in the router folder?

I made boilerplate for fiber as well as this https://github.com/firmanJS/boillerplate-fiber might be checked and considered
thank you

**Comment by Fenny** [comment]
Your boilerplate looks good, I would suggest making a PR to the official fiber repo to add your repo to the list.

And to answer your question, it's a personal preference. Since we do not have many routes in this example, I think it's fine to overview them in one file.
